name: update

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install hugo
        run: |
          sudo apt-get update
          sudo apt-get install git hugo -y
      - name: Update theme
        working-directory: hugo/themes/PaperMod
        run: |
          git submodule init
          git submodule update
      - name: Generate static files
        working-directory: hugo
        run: hugo
      - name: Sync files to server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: hugo/public/
          remote_path: /home/godot/sites/godot-blog/output/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
